//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConCung
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIACHINHANHANG
    {
        public string SDT { get; set; }
        public int STT { get; set; }
        public string HOTEN_NHAN { get; set; }
        public string SDT_NHAN { get; set; }
        public string DIACHI_NHAN { get; set; }
        public bool DIACHI_MACDINH { get; set; }
        public bool DIACHI_CONGTY { get; set; }
    
        public virtual BOME BOME { get; set; }
    }
}
