//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConCung
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
        }
    
        public string MA_DH { get; set; }
        public string SDT { get; set; }
        public string TINHTRANG { get; set; }
        public string MA_PHIEU { get; set; }
        public Nullable<double> TIENHANG { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual BOME BOME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual PHIEUGGQT PHIEUGGQT { get; set; }
    }
}
