//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConCung
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO
    {
        public string MA_ST { get; set; }
        public string MA_SP { get; set; }
        public int SOLUONGTON { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual SIEUTHI SIEUTHI { get; set; }
    }
}
