//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConCung
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
            this.CHITIETSPs = new HashSet<CHITIETSP>();
            this.KHOes = new HashSet<KHO>();
            this.SANPHAM1 = new HashSet<SANPHAM>();
        }
    
        public string MA_SP { get; set; }
        public string TEN_SP { get; set; }
        public string MIEUTA { get; set; }
        public string MA_LOAI { get; set; }
        public string MA_TH { get; set; }
        public bool COMBO { get; set; }
        public string MA_KM { get; set; }
        public Nullable<double> GIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSP> CHITIETSPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHO> KHOes { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM1 { get; set; }
        public virtual SANPHAM SANPHAM2 { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
