-- xem luong
use CONCUNG
go 

DECLARE @SOLANDD AS INT
	SET @SOLANDD = (SELECT COUNT(NGAYDD) FROM DIEM_DANH WHERE SDT = '0168087505' AND MONTH(NGAYDD) = 1 AND YEAR(NGAYDD) = YEAR(GETDATE()))

	SELECT LUONG_NGAY * @SOLANDD
	FROM NHANVIEN
	WHERE SDT = '0168087505'
go


USE CONCUNG_INDEX_PARTITION
go
DECLARE @SOLANDD AS INT
	SET @SOLANDD = (SELECT COUNT(NGAYDD) FROM DIEM_DANH WHERE SDT = '0168087505' AND MONTH(NGAYDD) = 1 AND YEAR(NGAYDD) = YEAR(GETDATE()))

	SELECT LUONG_NGAY * @SOLANDD
	FROM NHANVIEN
	WHERE SDT = '0168087505'
go


CHECK_LUONG '0168087505',1