
USE CONCUNG
go
SELECT MA_DH,TINHTRANG,NHANVIEN FROM DONHANG WHERE  DONHANG.NHANVIEN IS NULL and TINHTRANG = N'Đang giao'
go



use CONCUNG_INDEX_PARTITION
go
SELECT MA_DH,TINHTRANG,NHANVIEN FROM DONHANG WHERE  DONHANG.NHANVIEN IS NULL and TINHTRANG = N'Đang giao'
go

use CONCUNG_INDEX_PARTITION
go
XEMDH_NHANVIEN_DANGGIAO
go