USE CONCUNG
go
SELECT * FROM DONHANG
WHERE SDT = '0167179778' AND TINHTRANG = N'Đang giao'
go

create nonclustered  index index_DONHANG_TINHTRANG
on DONHANG (TINHTRANG)

use CONCUNG_INDEX_PARTITION
go
SELECT * FROM DONHANG
WHERE SDT = '0167179778' AND TINHTRANG = N'Đang giao'
go

use CONCUNG_INDEX_PARTITION
go
XEMDH_DANG_GIAO '0167179778'
go