use CONCUNG
go
	SELECT GIA FROM SANPHAM
	WHERE MA_LOAI = 'LSP001'
	ORDER BY GIA ASC
go

use CONCUNG_INDEX_PARTITION
go
	SELECT GIA FROM SANPHAM
	WHERE MA_LOAI = 'LSP001'
	ORDER BY GIA ASC
go

use CONCUNG_INDEX_PARTITION
go
XEMSPTHEOGIA_TANG_LOAI 'LSP001'
go