USE CONCUNG
GO

CREATE TRIGGER TRG_INS_CHITIETDH ON CHITIETDH AFTER INSERT AS
BEGIN
	IF EXISTS (SELECT* FROM SANPHAM, inserted WHERE SANPHAM.MA_SP = inserted.MA_SP AND SOLUONGTON - SO_LUONG < 0)
	BEGIN
		RAISERROR (N'Vượt số lượng hàng có trong kho.', 16, 1)
		ROLLBACK TRAN
	END

	UPDATE SANPHAM
	SET SOLUONGTON = SOLUONGTON - (SELECT SUM(inserted.SO_LUONG) FROM inserted WHERE inserted.MA_SP = SANPHAM.MA_SP GROUP BY inserted.MA_SP)
	FROM inserted
	WHERE SANPHAM.MA_SP = inserted.MA_SP

	DECLARE @THANHTIEN TABLE (THANHTIEN FLOAT, MASP CHAR(15), MADH CHAR(15))
	INSERT @THANHTIEN(MASP, MADH)
	SELECT MA_SP, MA_DH FROM inserted

	UPDATE @THANHTIEN
	SET THANHTIEN = inserted.SO_LUONG * SANPHAM.GIA
	FROM inserted, SANPHAM
	WHERE inserted.MA_SP = SANPHAM.MA_SP AND SANPHAM.MA_SP = MASP

	SELECT*FROM @THANHTIEN

	UPDATE DONHANG
	SET TIENHANG = TIENHANG  + (SELECT SUM(THANHTIEN) FROM @THANHTIEN WHERE DONHANG.MA_DH = MADH)
	FROM inserted, SANPHAM
	WHERE inserted.MA_DH = DONHANG.MA_DH AND SANPHAM.MA_SP = inserted.MA_SP
END
GO

CREATE PROC SUDUNGPGGQT
	@MA_DH char(15),
	@MA_PHIEU char(6)
AS
BEGIN
	UPDATE DONHANG
	SET MA_PHIEU = @MA_PHIEU
	WHERE MA_DH = @MA_DH

	IF (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = @MA_PHIEU) < 1
	BEGIN
		UPDATE DONHANG
		SET THANHTIEN = TIENHANG - TIENHANG * (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = @MA_PHIEU) 
		WHERE MA_DH = @MA_DH
	END
	ELSE
		BEGIN
		UPDATE DONHANG
		SET THANHTIEN = TIENHANG - (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = @MA_PHIEU) 
		WHERE MA_DH = @MA_DH
	END
	
END
GO

CREATE PROC TIM_5_SIEUTHI
	@QUAN NVARCHAR(20)
AS
BEGIN
	SELECT TOP 5 TEN_ST, DIACHI_ST, TGMOCUA
	FROM SIEUTHI
	WHERE DIACHI_ST LIKE '%' + @QUAN
END
GO

CREATE TRIGGER TRG_INS_GIOHANG ON GIOHANG AFTER INSERT AS
BEGIN
	IF EXISTS (SELECT* FROM SANPHAM, inserted WHERE SANPHAM.MA_SP = inserted.MA_SP AND SOLUONGTON - SO_LUONG < 0)
	BEGIN
		RAISERROR (N'Vượt số lượng hàng có trong kho.', 16, 1)
		ROLLBACK TRAN
	END

	UPDATE SANPHAM
	SET SOLUONGTON = SOLUONGTON - (SELECT SUM(inserted.SO_LUONG) FROM inserted WHERE inserted.MA_SP = SANPHAM.MA_SP GROUP BY inserted.MA_SP)
	FROM inserted
	WHERE SANPHAM.MA_SP = inserted.MA_SP

	DECLARE @THANHTIEN TABLE (THANHTIEN FLOAT, MASP CHAR(15), MADH CHAR(15))
	INSERT @THANHTIEN(MASP, MADH)
	SELECT MA_SP, MA_DH FROM inserted

	UPDATE @THANHTIEN
	SET THANHTIEN = inserted.SO_LUONG * SANPHAM.GIA
	FROM inserted, SANPHAM
	WHERE inserted.MA_SP = SANPHAM.MA_SP AND SANPHAM.MA_SP = MASP

	SELECT*FROM @THANHTIEN

	UPDATE DONHANG
	SET TIENHANG = TIENHANG  + (SELECT SUM(THANHTIEN) FROM @THANHTIEN WHERE DONHANG.MA_DH = MADH)
	FROM inserted, SANPHAM
	WHERE inserted.MA_DH = DONHANG.MA_DH AND SANPHAM.MA_SP = inserted.MA_SP
END