use CONCUNG
GO

CREATE PROC XEMSP_LOAI
	@MALOAI CHAR(6)
AS
BEGIN
	SELECT * FROM SANPHAM SP
	WHERE SP.MA_LOAI = @MALOAI
END
GO

CREATE PROC XEMSP_LOAI_HANG
	@MALOAI CHAR(6),
	@MATH CHAR(6)
AS
BEGIN
	SELECT * FROM SANPHAM SP
	WHERE SP.MA_LOAI = @MALOAI AND SP.MA_TH = @MATH
END
GO

CREATE PROC XEMLOAI_CHA
AS
BEGIN
	SELECT TEN_LOAI FROM LOAISP
	WHERE LOAISP_CHA = NULL
END
GO

CREATE PROC XEMLOAI
	@MALOAI CHAR(6)
AS
BEGIN
	SELECT TEN_LOAI FROM LOAISP
	WHERE LOAISP_CHA = @MALOAI
END
GO

CREATE PROC XEMSPTHEOGIA_TANG_LOAI
	@MALOAI CHAR(6)
AS
BEGIN
	SELECT * FROM SANPHAM
	WHERE MA_LOAI = @MALOAI
	ORDER BY GIA ASC
END
GO

CREATE PROC XEMSPTHEOGIA_GIAM_LOAI
	@MALOAI CHAR(6)
AS
BEGIN
	SELECT * FROM SANPHAM
	WHERE MA_LOAI = @MALOAI
	ORDER BY GIA DESC
END
GO

CREATE PROC XEMSPTHEOGIA_TANG_LOAI_TH
	@MALOAI CHAR(6),
	@MATH CHAR(6)
AS
BEGIN
	SELECT * FROM SANPHAM
	WHERE MA_LOAI = @MALOAI AND MA_TH = @MATH
	ORDER BY GIA ASC
END
GO

CREATE PROC XEMSPTHEOGIA_GIAM_LOAI_TH
	@MALOAI CHAR(6),
	@MATH CHAR(6)
AS
BEGIN
	SELECT * FROM SANPHAM
	WHERE MA_LOAI = @MALOAI AND MA_TH = @MATH
	ORDER BY GIA DESC
END
GO

CREATE PROC THANHTOAN
	@MADH CHAR(10),
	@SDT CHAR(10)
AS
BEGIN
	INSERT DONHANG (MA_DH, SDT, TINHTRANG, TIENHANG, THANHTIEN)
	VALUES (@MADH, @SDT, N'Đang xác nhận', 0, 0)

	SELECT MA_SP, SOLUONG, THANH_GIA
	INTO #TEMP
	FROM GIOHANG
	WHERE SDT = @SDT

	SELECT MA_DH, MA_SP, SOLUONG, THANH_GIA INTO #TEMP2
	FROM #TEMP, DONHANG
	WHERE MA_DH = @MADH

	INSERT CHITIETDH(MA_DH, MA_SP, SO_LUONG, THANHGIA)
	SELECT MA_DH, MA_SP, SOLUONG, THANH_GIA FROM #TEMP2

	UPDATE DONHANG
	SET TIENHANG = (SELECT TONGTIEN FROM BOME WHERE SDT = @SDT)
	, THANHTIEN = (SELECT THANH_TIEN FROM BOME WHERE SDT = @SDT)
	, MA_PHIEU = (SELECT MA_PHIEU FROM BOME WHERE SDT = @SDT)
	WHERE MA_DH = @MADH

	DELETE GIOHANG
	WHERE SDT = @SDT

	UPDATE BOME
	SET MA_PHIEU = NULL
	, THANH_TIEN = 0
	, TONGTIEN = 0
	WHERE SDT = @SDT

END
GO