use CONCUNG
GO

CREATE PROC XEMSP_LOAI
	@MALOAI CHAR(6)
AS
BEGIN
	SELECT GIA FROM SANPHAM SP
	WHERE SP.MA_LOAI = @MALOAI
END
GO

CREATE PROC XEMSP_LOAI_HANG
	@MALOAI CHAR(6),
	@MATH CHAR(6)
AS
BEGIN
	SELECT * FROM SANPHAM SP
	WHERE SP.MA_LOAI = @MALOAI AND SP.MA_TH = @MATH
END
GO

CREATE PROC XEMLOAI_CHA
AS
BEGIN
	SELECT TEN_LOAI FROM LOAISP
	WHERE LOAISP_CHA = NULL
END
GO

CREATE PROC XEMLOAI
	@MALOAI CHAR(6)
AS
BEGIN
	SELECT TEN_LOAI FROM LOAISP
	WHERE LOAISP_CHA = @MALOAI
END
GO

CREATE PROC XEMSPTHEOGIA_TANG_LOAI
	@MALOAI CHAR(6)
AS
BEGIN
	SELECT GIA FROM SANPHAM
	WHERE MA_LOAI = @MALOAI
	ORDER BY GIA ASC
END
GO

CREATE PROC XEMSPTHEOGIA_GIAM_LOAI
	@MALOAI CHAR(6)
AS
BEGIN
	SELECT GIA FROM SANPHAM
	WHERE MA_LOAI = @MALOAI
	ORDER BY GIA DESC
END
GO

CREATE PROC XEMSPTHEOGIA_TANG_LOAI_TH
	@MALOAI CHAR(6),
	@MATH CHAR(6)
AS
BEGIN
	SELECT * FROM SANPHAM
	WHERE MA_LOAI = @MALOAI AND MA_TH = @MATH
	ORDER BY GIA ASC
END
GO

CREATE PROC XEMSPTHEOGIA_GIAM_LOAI_TH
	@MALOAI CHAR(6),
	@MATH CHAR(6)
AS
BEGIN
	SELECT * FROM SANPHAM
	WHERE MA_LOAI = @MALOAI AND MA_TH = @MATH
	ORDER BY GIA DESC
END
GO

CREATE PROC THANHTOAN
	@MADH CHAR(10),
	@SDT CHAR(10)
AS
BEGIN
	INSERT DONHANG (MA_DH, SDT, TINHTRANG, TIENHANG, THANHTIEN, NGAYLAP)
	VALUES (@MADH, @SDT, N'Đang giao', 0, 0, GETDATE())

	SELECT MA_SP, SOLUONG, THANH_GIA
	INTO #TEMP
	FROM GIOHANG
	WHERE SDT = @SDT

	SELECT MA_DH, MA_SP, SOLUONG, THANH_GIA INTO #TEMP2
	FROM #TEMP, DONHANG
	WHERE MA_DH = @MADH

	INSERT CHITIETDH(MA_DH, MA_SP, SO_LUONG, THANHGIA)
	SELECT MA_DH, MA_SP, SOLUONG, THANH_GIA FROM #TEMP2

	UPDATE DONHANG
	SET TIENHANG = (SELECT TONGTIEN FROM BOME WHERE SDT = @SDT)
	, THANHTIEN = (SELECT THANH_TIEN FROM BOME WHERE SDT = @SDT)
	, MA_PHIEU = (SELECT MA_PHIEU FROM BOME WHERE SDT = @SDT)
	WHERE MA_DH = @MADH

	DELETE GIOHANG
	WHERE SDT = @SDT

	UPDATE BOME
	SET MA_PHIEU = NULL
	, THANH_TIEN = 0
	, TONGTIEN = 0
	WHERE SDT = @SDT

END
GO

CREATE PROC XOASP
	@MA_SP CHAR(6)
AS
BEGIN
	DELETE CHITIETDH WHERE MA_SP = @MA_SP
	DELETE KHO WHERE MA_SP = @MA_SP
	DELETE SANPHAM WHERE MA_SP = @MA_SP
END
GO

CREATE PROC THEMSP
	@MA_SP CHAR(6),
	@TEN_SP NVARCHAR(250),
	@MIEUTA NVARCHAR(MAX),
	@MA_LOAI CHAR(6),
	@MA_TH CHAR(6),
	@COMBO BIT,
	@MA_KM CHAR(10),
	@GIA FLOAT,
	@IMAGE VARCHAR(50)
AS
BEGIN
	INSERT SANPHAM (MA_SP,TEN_SP,MIEUTA,MA_LOAI,MA_TH,COMBO,MA_KM,GIA,SOLUONGTON,IMAGE)
	VALUES (@MA_SP,@TEN_SP,@MIEUTA,@MA_LOAI,@MA_TH,@COMBO,@MA_KM,@GIA, 0, @IMAGE)
END
GO

CREATE PROC CAPNHATGIA
	@MA_SP CHAR(6),
	@GIA FLOAT
AS
BEGIN
	UPDATE SANPHAM
	SET GIA = @GIA
	WHERE MA_SP = @MA_SP
END
GO

CREATE PROC DOANHTHU_THANG
	@THANG INT,
	@NAM INT
AS
BEGIN
	SELECT SUM(THANHTIEN)
	FROM DONHANG
	WHERE MONTH(NGAYLAP) = @THANG AND YEAR(NGAYLAP) = @NAM
END
GO

CREATE PROC DOANHTHU_NAM
	@NAM INT
AS
BEGIN
	SELECT SUM(THANHTIEN)
	FROM DONHANG
	WHERE YEAR(NGAYLAP) = @NAM
END
GO

CREATE PROC KIEMTRA_SP_CO_HANG
	@MA_SP CHAR(10)
AS
BEGIN
	SELECT TEN_ST
	FROM SIEUTHI,KHO
	WHERE KHO.MA_SP = @MA_SP AND KHO.MA_ST = SIEUTHI.MA_ST
END
GO

CREATE PROC THEM_KHUYENMAI
	@MA_PHIEU CHAR(6),
	@TEN_PHIEU NVARCHAR(50),
	@GIATRI_PHIEU FLOAT
AS
BEGIN
	INSERT PHIEUGGQT(MA_PHIEU, TEN_PHIEU, GIATRI_PHIEU)
	VALUES (@MA_PHIEU, @TEN_PHIEU, @GIATRI_PHIEU)
END
GO

CREATE PROC CHECKIN
	@SDT CHAR(10)
AS
BEGIN
	INSERT DIEM_DANH(SDT, NGAYDD)
	VALUES (@SDT, GETDATE())
END
GO

CREATE PROC CHECK_LUONG
	@SDT CHAR(10),
	@THANG INT
AS
BEGIN
	DECLARE @SOLANDD AS INT
	SET @SOLANDD = (SELECT COUNT(NGAYDD) FROM DIEM_DANH WHERE SDT = @SDT AND MONTH(NGAYDD) = @THANG AND YEAR(NGAYDD) = YEAR(GETDATE()))

	SELECT LUONG_NGAY * @SOLANDD
	FROM NHANVIEN
	WHERE SDT = @SDT
END
GO

CREATE PROC XEMDH_DANG_GIAO
	@SDT CHAR(10)
AS
BEGIN
	SELECT * FROM DONHANG
	WHERE SDT = @SDT AND TINHTRANG = N'Đang giao'
END
GO

CREATE PROC XEMDH_DANG_GIAO_BY_date
	@SDT CHAR(10),
	@startdate date,
	@endate date
AS
BEGIN
	SELECT * FROM DONHANG
	WHERE SDT = @SDT AND TINHTRANG = N'Đang giao'
	and NGAYLAP>=@startdate and  NGAYLAP<=@endate
END
GO

CREATE PROC XEMDH_HOANTHANH
	@SDT CHAR(10)
AS
BEGIN
	SELECT * FROM DONHANG
	WHERE SDT = @SDT AND TINHTRANG = N'Hoàn thành'
END
GO

CREATE PROC XEMDH_NHANVIEN_DANGGIAO
AS
BEGIN
	SELECT MA_DH,TINHTRANG,NHANVIEN FROM DONHANG WHERE  DONHANG.NHANVIEN IS NULL and TINHTRANG = N'Đang giao'
END
GO

CREATE PROC CHONDH_NHANVIEN
	@MADH CHAR(10),
	@MANV CHAR(10)
AS
BEGIN
	UPDATE DONHANG
	SET NHANVIEN = @MANV
	WHERE MA_DH = @MADH
END
GO

CREATE PROC CAPNHATDON
	@MADH CHAR(10)
AS
BEGIN
	UPDATE DONHANG
	SET TINHTRANG = N'Hoàn thành'
	WHERE MA_DH = @MADH
END
GO

CREATE PROC XEMDH_HOANTHANH_NHANVIEN
	@SDT CHAR(10)
AS
BEGIN
	SELECT * FROM DONHANG
	WHERE NHANVIEN = @SDT AND TINHTRANG = N'Hoàn thành'
END
GO


CREATE PROC NHAPTHEMSP
	@PHIEUNHAP CHAR(6),
	@MASP CHAR(10),
	@QUANLY CHAR(10),
	@SOLUONG INT
AS
BEGIN
	INSERT NHAPHANG(PHIEUNHAP, MA_SP, QUANLY, SOLUONG, NGAYNHAP)
	VALUES (@PHIEUNHAP, @MASP, @QUANLY, @SOLUONG, GETDATE())

	UPDATE SANPHAM
	SET SOLUONGTON = SOLUONGTON + @SOLUONG
	WHERE MA_SP = @MASP
END
GO

CREATE PROC XEMLICHSUNHAP_THANG
	@THANG INT,
	@NAM INT
AS
BEGIN
	SELECT * FROM NHAPHANG
	WHERE MONTH(NGAYNHAP) = @THANG AND YEAR(NGAYNHAP) = @NAM
END
GO

CREATE PROC XEMLICHSUNHAP_NAM
	@NAM INT
AS
BEGIN
	SELECT * FROM NHAPHANG
	WHERE YEAR(NGAYNHAP) = @NAM
END
GO

CREATE PROC XEMLICHSUNHAP
AS
BEGIN
	SELECT * FROM NHAPHANG
END
GO

CREATE PROC XEMSP_TONKHO
	@MASP CHAR(10)
AS
BEGIN
	SELECT SOLUONGTON FROM SANPHAM
	WHERE MA_SP = @MASP
END
GO

CREATE PROC XEMNGAYLAP_DANGGIAO
AS
BEGIN
	select NGAYLAP
    from DONHANG
    where TINHTRANG like N'Đang giao'
END
GO

CREATE PROC TENSP_LOAI
		@LOAI char(6)
AS
BEGIN
	SELECT TEN_SP FROM SANPHAM SP
	WHERE SP.MA_LOAI = @LOAI
END
GO


CREATE PROC TIMSP_BANGTEN
		@TEN nvarchar(250)
AS
BEGIN
	Select TEN_SP 
	from SANPHAM
	where TEN_SP like @TEN
END
GO

CREATE TRIGGER TRG_INS_CHITIETDH ON CHITIETDH AFTER INSERT AS
BEGIN
	IF EXISTS (SELECT* FROM SANPHAM, inserted WHERE SANPHAM.MA_SP = inserted.MA_SP AND SOLUONGTON - SO_LUONG < 0)
	BEGIN
		RAISERROR (N'Vượt số lượng hàng có trong kho.', 16, 1)
		ROLLBACK TRAN
	END

	UPDATE SANPHAM
	SET SOLUONGTON = SOLUONGTON - (SELECT SUM(inserted.SO_LUONG) FROM inserted WHERE inserted.MA_SP = SANPHAM.MA_SP GROUP BY inserted.MA_SP)
	FROM inserted
	WHERE SANPHAM.MA_SP = inserted.MA_SP

	DECLARE @THANHTIEN TABLE (THANHTIEN FLOAT, MASP CHAR(15), MADH CHAR(15))
	INSERT @THANHTIEN(MASP, MADH)
	SELECT MA_SP, MA_DH FROM inserted

	UPDATE @THANHTIEN
	SET THANHTIEN = inserted.SO_LUONG * SANPHAM.GIA
	FROM inserted, SANPHAM
	WHERE inserted.MA_SP = SANPHAM.MA_SP AND SANPHAM.MA_SP = MASP

	SELECT*FROM @THANHTIEN

	UPDATE DONHANG
	SET TIENHANG = TIENHANG  + (SELECT SUM(THANHTIEN) FROM @THANHTIEN WHERE DONHANG.MA_DH = MADH)
	FROM inserted, SANPHAM
	WHERE inserted.MA_DH = DONHANG.MA_DH AND SANPHAM.MA_SP = inserted.MA_SP
END
GO

CREATE PROC SUDUNGPGGQT
	@MA_DH char(15),
	@MA_PHIEU char(6)
AS
BEGIN
	UPDATE DONHANG
	SET MA_PHIEU = @MA_PHIEU
	WHERE MA_DH = @MA_DH

	IF (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = @MA_PHIEU) < 1
	BEGIN
		UPDATE DONHANG
		SET THANHTIEN = TIENHANG - TIENHANG * (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = @MA_PHIEU) 
		WHERE MA_DH = @MA_DH
	END
	ELSE
		BEGIN
		UPDATE DONHANG
		SET THANHTIEN = TIENHANG - (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = @MA_PHIEU) 
		WHERE MA_DH = @MA_DH
	END
	
END
GO

CREATE PROC TIM_5_SIEUTHI
	@QUAN NVARCHAR(20)
AS
BEGIN
	SELECT TOP 5 TEN_ST, DIACHI_ST, TGMOCUA
	FROM SIEUTHI
	WHERE DIACHI_ST LIKE '%' + @QUAN
END
GO

CREATE PROC THEM_PHIEU_VAO_GIO
	@SDT CHAR(10),
	@MA_PHIEU CHAR(6)
AS
BEGIN
	UPDATE BOME
	SET MA_PHIEU = @MA_PHIEU
	WHERE SDT = @SDT

	IF (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = @MA_PHIEU) < 1
	BEGIN
		UPDATE BOME
		SET THANH_TIEN = TONGTIEN - TONGTIEN * (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = @MA_PHIEU) 
		WHERE SDT = @SDT
	END
	ELSE
		BEGIN
		UPDATE BOME
		SET THANH_TIEN = TONGTIEN - (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = @MA_PHIEU) 
		WHERE SDT = SDT
	END
END
GO

CREATE PROC GO_PHIEU_KHOI_GIO
	@SDT CHAR(10)
AS
BEGIN
	DECLARE @MA_PHIEU CHAR(6)
	SET @MA_PHIEU = (SELECT MA_PHIEU FROM BOME WHERE SDT = @SDT)
	
	UPDATE BOME
	SET MA_PHIEU = NULL, THANH_TIEN = TONGTIEN
	WHERE SDT = @SDT
END
GO

CREATE TRIGGER TRG_INS_GIOHANG ON GIOHANG AFTER INSERT, UPDATE AS
BEGIN
	IF EXISTS (SELECT* FROM SANPHAM, inserted WHERE SANPHAM.MA_SP = inserted.MA_SP AND SOLUONGTON - SOLUONG < 0)
	BEGIN
		RAISERROR (N'Vượt số lượng hàng có trong kho.', 16, 1)
		ROLLBACK TRAN
	END
	UPDATE GIOHANG
	SET THANH_GIA = GIOHANG.SOLUONG * (SELECT GIA FROM SANPHAM WHERE SANPHAM.MA_SP = inserted.MA_SP)
	FROM inserted
	WHERE inserted.MA_SP = GIOHANG.MA_SP

	UPDATE BOME
	SET TONGTIEN = (SELECT SUM(THANH_GIA) FROM GIOHANG WHERE GIOHANG.SDT = inserted.SDT)
	FROM inserted
	WHERE BOME.SDT = inserted.SDT

	UPDATE BOME
	SET THANH_TIEN = TONGTIEN
	FROM inserted
	WHERE BOME.SDT = inserted.SDT AND MA_PHIEU IS NULL

	UPDATE BOME
	SET THANH_TIEN = TONGTIEN - TONGTIEN * (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = BOME.MA_PHIEU) 
	FROM inserted
	WHERE BOME.SDT = inserted.SDT AND BOME.MA_PHIEU IS NOT NULL AND (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = BOME.MA_PHIEU) < 1

	UPDATE BOME
	SET THANH_TIEN = TONGTIEN - TONGTIEN * (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = BOME.MA_PHIEU) 
	FROM inserted
	WHERE BOME.SDT = inserted.SDT AND BOME.MA_PHIEU IS NOT NULL AND (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = BOME.MA_PHIEU) >= 1
END
GO

CREATE TRIGGER TRG_DEL_GIOHANG ON GIOHANG AFTER DELETE AS
BEGIN
	UPDATE BOME
	SET TONGTIEN = TONGTIEN - (SELECT SUM(THANH_GIA) FROM deleted WHERE BOME.SDT = deleted.SDT)
	FROM deleted
	WHERE BOME.SDT = deleted.SDT

	UPDATE BOME
	SET THANH_TIEN = TONGTIEN
	FROM deleted
	WHERE BOME.SDT = deleted.SDT AND MA_PHIEU IS NULL

	UPDATE BOME
	SET THANH_TIEN = TONGTIEN - TONGTIEN * (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = BOME.MA_PHIEU) 
	FROM deleted
	WHERE BOME.SDT = deleted.SDT AND BOME.MA_PHIEU IS NOT NULL AND (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = BOME.MA_PHIEU) < 1

	UPDATE BOME
	SET THANH_TIEN = TONGTIEN - TONGTIEN * (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = BOME.MA_PHIEU) 
	FROM deleted
	WHERE BOME.SDT = deleted.SDT AND BOME.MA_PHIEU IS NOT NULL AND (SELECT GIATRI_PHIEU FROM PHIEUGGQT WHERE MA_PHIEU = BOME.MA_PHIEU) >= 1

END
GO